FROM continuumio/miniconda3:4.8.2 AS condabuild
COPY nextstrain/workflow/envs/nextstrain.yaml /environment.yml
RUN /opt/conda/bin/conda update conda \
  && /opt/conda/bin/conda install mamba -c conda-forge \
  && /opt/conda/bin/mamba env create -f /environment.yml -n nextstrain \
  && /opt/conda/bin/mamba create -c bioconda -c conda-forge -n snakemake snakemake-minimal=5.13

FROM debian:buster-slim
COPY nextstrain/ /nextstrain
COPY --from=condabuild /opt/conda/envs/nextstrain /opt/conda/envs/nextstrain
COPY --from=condabuild /opt/conda/envs/snakemake /opt/conda/envs/snakemake
ENV PATH=/opt/conda/envs/nextstrain/bin:/opt/conda/envs/snakemake/bin:$PATH
