FROM continuumio/miniconda3:4.10.3 AS condabuild
COPY ncov2019-artic-nf/environments/extras.yml /extras.yml
COPY ncov2019-artic-nf/environments/nanopore/environment.yml /nanopore.yml
RUN /opt/conda/bin/conda update conda && \
/opt/conda/bin/conda install mamba -c conda-forge && \
/opt/conda/bin/mamba env create -f /nanopore.yml && \
/opt/conda/bin/mamba env update -f /extras.yml -n artic

# reinstall these two packages to their latest version, as the conda-selected downgraded ones fail to run
RUN /opt/conda/bin/mamba install -y -c conda-forge -c bioconda cutadapt==3.1 dnaio==0.4.4 openjdk=11.0.8 -n artic

FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y git procps wget \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/artic /opt/conda/envs/artic
ENV PATH=/opt/conda/envs/artic/bin:$PATH
COPY ncov2019-artic-nf/bin/qc.py /opt/conda/envs/artic/bin

RUN wget -qO- https://get.nextflow.io | bash && chmod +x nextflow && mv nextflow /usr/bin

COPY . /app
WORKDIR /app/ncov2019-artic-nf
