FROM node:12

ENV HOST=0.0.0.0
EXPOSE 4000

RUN apt-get update \
  && apt-get install -y --no-install-recommends git \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/nextstrain/auspice.git \
  && cd auspice \
  && npm --global config set user root \
  && npm --global install . \
  && auspice build
