FROM continuumio/miniconda3:4.8.2 AS condabuild-nextstrain
COPY nextstrain/workflow/envs/nextstrain.yaml /environment.yml
RUN /opt/conda/bin/conda update conda \
  && /opt/conda/bin/conda install mamba -c conda-forge \
  && /opt/conda/bin/mamba env create -f /environment.yml -n nextstrain


FROM continuumio/miniconda3:4.8.2 AS condabuild-snakemake
RUN /opt/conda/bin/conda update conda \
  && /opt/conda/bin/conda install mamba -c conda-forge \
  && /opt/conda/bin/mamba create -c conda-forge -c bioconda -n snakemake snakemake


FROM debian:buster-slim
COPY nextstrain/ /nextstrain
COPY --from=condabuild-nextstrain /opt/conda/envs/nextstrain /opt/conda/envs/nextstrain
COPY --from=condabuild-snakemake /opt/conda/envs/snakemake /opt/conda/envs/snakemake
ENV PATH=/opt/conda/envs/nextstrain/bin:/opt/conda/envs/snakemake/bin:$PATH
