# primer index columns
PRIMER_NAME = "primer_name"
FASTA_PATH = "fasta_path"
PICKLE_PATH = "pickle_path"
TOTAL_NUM_PRIMER = "total_num_primers"
PRIMER_INDEX_COLS = [
    PRIMER_NAME,
    FASTA_PATH,
    PICKLE_PATH,
    TOTAL_NUM_PRIMER,
]

# primer autodetection output columns
PRIMER_AUTODETECTION_SAMPLE_ID_COL = "sample_id"
PRIMER_AUTODETECTION_PRIMER_INPUT_COL = "primer_input"
PRIMER_AUTODETECTION_PRIMER_COL = "primer_detected"
PRIMER_AUTODETECTION_NUMREADS_COL = "primer_numreads"
PRIMER_AUTODETECTION_UNIQUE_NUMREADS_COL = "primer_unique_numreads"
PRIMER_AUTODETECTION_AMBIGUOUS_NUMREADS_COL = "primer_ambiguous_numreads"
PRIMER_AUTODETECTION_COVERAGE_COL = "primer_coverage"
EXPECTED_PRIMER_AUTODETECTION_HEADERS = {
    PRIMER_AUTODETECTION_SAMPLE_ID_COL,
    PRIMER_AUTODETECTION_PRIMER_INPUT_COL,
    PRIMER_AUTODETECTION_PRIMER_COL,
    PRIMER_AUTODETECTION_NUMREADS_COL,
    PRIMER_AUTODETECTION_UNIQUE_NUMREADS_COL,
    PRIMER_AUTODETECTION_AMBIGUOUS_NUMREADS_COL,
    PRIMER_AUTODETECTION_COVERAGE_COL,
}
