
Vagrant.configure("2") do |config|
    # centos config
    config.vm.define "centos" do |centos|
      centos.vm.box = "geerlingguy/centos7"
        centos.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = 2048
          vb.cpus = 2
      end
  
      centos.vm.provision "ansible" do |ansible|
        ansible.playbook = "test/test.yml"
        ansible.extra_vars = {
          pipeline_user: "pipeline",
          github_username: "",
          github_password_or_token: "",
          aws_key_id: "",
          aws_private_key: ""
        }
        ansible.extra_vars = '../../vars/env_vars.yml'
        ansible.verbose = true
      end
    end
  end