
Vagrant.configure("2") do |config|
    # centos config
    config.vm.define "centos" do |centos|
      centos.vm.box = "geerlingguy/centos7"
        centos.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = 2048
          vb.cpus = 2
      end

      config.vm.synced_folder "../../../../covid-pipeline/", "/home/vagrant/covid-pipeline/"
      centos.vm.provision "ansible" do |ansible|
        ansible.playbook = "test/test.yml"
        ansible.extra_vars = '../../vars/env_vars.yml'
        ansible.extra_vars = {
          covid_pipeline_rootdir: "covid_pipeline_rootdir_value1",
          db_host: "localhost",
          db_name: "bahrain_sars_cov_2",
          db_user: "postgres",
          db_port: "5432",
          db_password: "test12345",
          covid_pipeline_rootdir: "${HOME}/covid-pipeline",
          covid_pipeline_fastq_path: "${HOME}/Bahrain_COVID_s3_data_lite/sample_data",
          covid_pipeline_workdir: "${HOME}/covid-pipeline-workdir",
          covid_pipeline_reports_path: "${HOME}/covid-pipeline-reports"
        }
        ansible.verbose = true
      end
    end
  end
