
Vagrant.configure("2") do |config|
    # centos config
    config.vm.define "centos" do |centos|
      centos.vm.box = "geerlingguy/centos7"
        centos.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = 2048
          vb.cpus = 2
      end

      config.vm.synced_folder "../../../../psga/", "/home/vagrant/psga/"
      centos.vm.provision "ansible" do |ansible|
        ansible.playbook = "test/test.yml"
        ansible.extra_vars = '../../vars/env_vars.yml'
        ansible.extra_vars = {
          psga_root_path: "psga_root_path_value1",
          db_host: "localhost",
          db_name: "psga_db",
          db_user: "postgres",
          db_port: "5432",
          db_password: "test12345",
          psga_root_path: "${HOME}/psga",
          psga_input_path: "${HOME}/psga-input",
          psga_output_path: "${HOME}/psga-output",
          psga_reports_path: "${HOME}/psga-reports"
        }
        ansible.verbose = true
      end
    end
  end
