FROM continuumio/miniconda3:4.10.3 AS condabuild

ARG pangolin_commit=a85856bf4dbb128d8070c2557da18c2ab1b3686b

RUN git clone https://github.com/cov-lineages/pangolin.git \
  && cd pangolin \
  && git checkout ${pangolin_commit}

RUN conda install mamba -c conda-forge \
  && mamba env create -f pangolin/environment.yml -n pangolin

FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends git procps ca-certificates \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/pangolin /opt/conda/envs/pangolin
COPY --from=condabuild /pangolin /pangolin
ENV PATH=/opt/conda/envs/pangolin/bin:$PATH

ARG pangolin_data_commit=4d7220a4b0a67cec0d718b7415cafbc81120af38
ARG scorpio_commit=300d4a8609d9e8c96a2bad37655063365d296eed
ARG constellations_commit=61e2a6b12abc63ee488712f60a2c8d88d69bb9bc

RUN cd /pangolin \
  && python setup.py install \
  && pip install --force-reinstall git+https://github.com/cov-lineages/pangolin-data.git@${pangolin_data_commit} \
  && pip install --force-reinstall git+https://github.com/cov-lineages/scorpio.git@${scorpio_commit} \
  && pip install --force-reinstall git+https://github.com/cov-lineages/constellations.git@${constellations_commit}
