FROM condaforge/mambaforge:4.14.0-0 AS condabuild

ARG pathogen
COPY docker/${pathogen}/read-it-and-keep.yml /environment.yml

RUN mamba env create -f /environment.yml -n custom_env \
  && conda clean --all -y

FROM debian:buster-slim

ARG pathogen

COPY --from=condabuild /opt/conda/envs/custom_env /opt/conda/envs/custom_env
ENV PATH=/opt/conda/envs/custom_env/bin:$PATH

COPY data/${pathogen}/read-it-and-keep/* /
COPY scripts/common /app/scripts/common
