FROM postgres:11.14

RUN apt-get update \
  && apt-get install --yes --no-install-recommends sqitch libdbd-pg-perl postgresql-client libdbd-sqlite3-perl sqlite3 \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

env PGUSER=postgres

WORKDIR /sqitch

COPY sqitch .
