FROM 566277102435.dkr.ecr.eu-west-2.amazonaws.com/congenica/psga-nonprod/bactopia:dev_latest

ARG pathogen

# This command takes about 1hr to run
RUN bactopia datasets --species "Staphylococcus aureus" --include_genus

COPY docker/${pathogen}/${pathogen}.yml /requirements.yml
mamba env update -n base -f requirements.yml
