FROM continuumio/miniconda3:4.10.3 AS condabuild

ARG ncov=ncov2019-artic-nf
ARG ncov_commit=3338ee7a3b9f6e33de621acf513c9cbd8b16debf

RUN git clone --recursive https://github.com/Congenica/${ncov}.git \
  && cd ${ncov} \
  && git checkout ${ncov_commit}

# Also reinstall these two packages to their latest version, as the conda-selected downgraded ones fail to run
RUN cd ${ncov}/environments \
  && conda install mamba -c conda-forge \
  && mamba env create -f illumina/environment.yml \
  && mamba env update -f extras.yml -n artic-ncov2019-illumina \
  && mamba install -y -c conda-forge -c bioconda cutadapt==3.1 dnaio==0.4.4 openjdk=11.0.8 -n artic-ncov2019-illumina


FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y git procps wget rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/artic-ncov2019-illumina /opt/conda/envs/artic-ncov2019-illumina
COPY --from=condabuild ${ncov} ${ncov}
ENV PATH=${ncov}/bin:/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH

RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v21.10.6/nextflow | bash && chmod +x nextflow && mv nextflow /usr/bin

ARG primer_schemes_commit=a60a1e1e73bde1971c680bd3d53076127dd63fc6
ARG pathogen=SARS-CoV-2
COPY docker/download_primer_schemes.sh .
RUN bash download_primer_schemes.sh ${primer_schemes_commit} ${pathogen}

COPY psga/sars_cov_2/ncov-illumina.config .
COPY psga/sars_cov_2/ncov-common.config .
