FROM python:3.9

# Also install a DB client and sqitch so that we can access the DB from this image
RUN apt-get update \
  && apt-get install --yes --no-install-recommends build-essential procps wget default-jre openjdk-11-jre-headless libpq-dev sqitch libdbd-pg-perl postgresql-client libdbd-sqlite3-perl sqlite3 rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# fetch a version of nextflow including the nf-amazon plugin
RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v21.10.6/nextflow-21.10.6-all | bash && chmod +x nextflow && mv nextflow /usr/bin
