FROM continuumio/miniconda3:4.10.3 AS condabuild

ARG ncov=ncov2019-artic-nf
ARG ncov_commit=afa4c7f2eb176212444bd6afe785a9251f95f792

RUN git clone --recursive https://github.com/Congenica/${ncov}.git \
  && cd ${ncov} \
  && git checkout ${ncov_commit}

# Also reinstall these two packages to their latest version, as the conda-selected downgraded ones fail to run
# pin muscle to 3.8 as this is what the artic code uses, but the dependencies above install the 5.1 which does not work
RUN cd ${ncov}/environments \
  && conda install mamba -c conda-forge \
  && mamba env create -f nanopore/environment.yml \
  && mamba env update -f extras.yml -n artic \
  && mamba install -y -c conda-forge -c bioconda cutadapt==3.1 dnaio==0.4.4 muscle==3.8.1551 openjdk=11.0.8 -n artic


FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y git procps wget rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/artic /opt/conda/envs/artic
COPY --from=condabuild ${ncov} ${ncov}
ENV PATH=${ncov}/bin:/opt/conda/envs/artic/bin:$PATH

# install medaka models
RUN medaka tools download_models \
        --models r103_fast_variant_g507 r103_hac_variant_g507 r103_prom_variant_g3210 r103_sup_variant_g507 \
                 r941_min_fast_variant_g507 r941_min_hac_variant_g507 r941_min_sup_variant_g507 \
                 r941_prom_fast_variant_g507 r941_prom_hac_variant_g507 r941_prom_sup_variant_g507 \
                 r941_prom_variant_g303 r941_prom_variant_g322 r941_prom_variant_g360


RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v21.10.6/nextflow | bash && chmod +x nextflow && mv nextflow /usr/bin

ARG primer_schemes_commit=a60a1e1e73bde1971c680bd3d53076127dd63fc6
ARG pathogen=SARS-CoV-2
COPY docker/download_primer_schemes.sh .
RUN bash download_primer_schemes.sh ${primer_schemes_commit} ${pathogen}

COPY psga/sars_cov_2/ncov-nanopore.config .
COPY psga/sars_cov_2/ncov-common.config .
