FROM condaforge/mambaforge:4.14.0-0 AS condabuild

ARG pathogen
COPY docker/${pathogen}/ncov2019-artic-nf/environments/illumina/environment.yml /environment.yml
# Also reinstall packages to pinned versions, as the conda-selected downgraded ones fail to run
RUN mamba env create -f /environment.yml -n custom_env \
  && mamba install -y -c conda-forge -c bioconda cutadapt==3.1 dnaio==0.4.4 -n custom_env \
  && conda clean --all -y


FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends procps rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/custom_env /opt/conda/envs/custom_env

ENV PATH=/ncov2019-artic-nf/bin:/opt/conda/envs/custom_env/bin:$PATH
# otherwise python click complains
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ARG pathogen
COPY docker/${pathogen}/ncov2019-artic-nf /ncov2019-artic-nf
COPY psga/${pathogen}/ncov-illumina.config psga/${pathogen}/ncov-common.config /
COPY data/${pathogen}/ncov2019-artic-nf/* /
COPY data/${pathogen}/primer_schemes /primer_schemes
COPY scripts/common /app/scripts/common

# install awscli here because the conda version requires a much more updated Python version
RUN pip install awscli==1.20.50
