FROM condaforge/mambaforge:4.14.0-0 AS condabuild

ARG ncov=ncov2019-artic-nf
ARG ncov_commit=afa4c7f2eb176212444bd6afe785a9251f95f792

RUN git clone --recursive https://github.com/Congenica/${ncov}.git \
  && cd ${ncov} \
  && git checkout ${ncov_commit}

# Also reinstall packages to pinned versions, as the conda-selected downgraded ones fail to run
RUN cd ${ncov}/environments \
  && mamba env create -f illumina/environment.yml \
  && mamba env update -f extras.yml -n artic-ncov2019-illumina \
  && mamba install -y -c conda-forge -c bioconda cutadapt==3.1 dnaio==0.4.4 -n artic-ncov2019-illumina \
  && conda clean --all -y


FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends git procps wget rename default-jre \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/artic-ncov2019-illumina /opt/conda/envs/artic-ncov2019-illumina
COPY --from=condabuild ${ncov} ${ncov}
ENV PATH=${ncov}/bin:/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH

RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v21.10.6/nextflow | bash && chmod +x nextflow && mv nextflow /usr/bin

COPY docker/download_primer_schemes.sh psga/sars_cov_2/ncov-illumina.config psga/sars_cov_2/ncov-common.config /
ARG primer_schemes_commit=a60a1e1e73bde1971c680bd3d53076127dd63fc6
ARG pathogen=SARS-CoV-2

RUN bash download_primer_schemes.sh ${primer_schemes_commit} ${pathogen}
