FROM condaforge/mambaforge:4.14.0-0 AS condabuild

COPY docker/bactopia/bactopia.yml /environment.yml

RUN mamba env create -f /environment.yml -n custom_env \
  && conda clean --all -y

# activate the environment. Note conda run is an "experimental" command
SHELL ["conda", "run", "-n", "custom_env", "/bin/bash", "-c"]

# Download bactopia workflows.
# When updating bactopia, check the list of these workflows in the locations reported below
# This is computationally intensive (at least 2h) and generates a large image ~20GB
# see: bin/bactopia/bactopia-download.py
# --use-defaults is required in order to build environments to the default Bactopia location,
# hence skipping the activation of the environment

# (1) Download bactopia subworkflows (bactopia repo: modules/local/bactopia).
# These subworkflows belong to the main "bactopia" workflow (which is the default workflow executed by the bactopia command)
# Here, I make this explicit in order to avoid confusion
RUN bactopia download --use-defaults --verbose --wf bactopia


# (2) Download bactopia workflows (bactopia repo: modules/nf-core/modules)
# These workflows are not part of the main bactopia workflow
# These are passed with `--wf <workflow>`
# The exact selection of these workflows depends on the required analyses.
# RUN bactopia download --use-defaults --verbose --wf abricate
# RUN bactopia download --use-defaults --verbose --wf agrvate
# RUN bactopia download --use-defaults --verbose --wf amrfinderplus
# RUN bactopia download --use-defaults --verbose --wf ariba
# RUN bactopia download --use-defaults --verbose --wf bakta
# RUN bactopia download --use-defaults --verbose --wf busco
RUN bactopia download --use-defaults --verbose --wf checkm
# RUN bactopia download --use-defaults --verbose --wf clonalframeml
# RUN bactopia download --use-defaults --verbose --wf csvtk
# RUN bactopia download --use-defaults --verbose --wf custom
# RUN bactopia download --use-defaults --verbose --wf ectyper
# RUN bactopia download --use-defaults --verbose --wf eggnog
# RUN bactopia download --use-defaults --verbose --wf emmtyper
# RUN bactopia download --use-defaults --verbose --wf fastani
# RUN bactopia download --use-defaults --verbose --wf gamma
# RUN bactopia download --use-defaults --verbose --wf genotyphi
# RUN bactopia download --use-defaults --verbose --wf gtdbtk
# RUN bactopia download --use-defaults --verbose --wf gubbins
# RUN bactopia download --use-defaults --verbose --wf hicap
# RUN bactopia download --use-defaults --verbose --wf hpsuissero
# RUN bactopia download --use-defaults --verbose --wf iqtree
# RUN bactopia download --use-defaults --verbose --wf ismapper
# RUN bactopia download --use-defaults --verbose --wf kleborate
# RUN bactopia download --use-defaults --verbose --wf kraken2
# RUN bactopia download --use-defaults --verbose --wf legsta
# RUN bactopia download --use-defaults --verbose --wf lissero
# RUN bactopia download --use-defaults --verbose --wf mash
# RUN bactopia download --use-defaults --verbose --wf mashtree
# RUN bactopia download --use-defaults --verbose --wf mcroni
# RUN bactopia download --use-defaults --verbose --wf meningotype
RUN bactopia download --use-defaults --verbose --wf mlst
# RUN bactopia download --use-defaults --verbose --wf mobsuite
RUN bactopia download --use-defaults --verbose --wf mykrobe
# RUN bactopia download --use-defaults --verbose --wf ncbigenomedownload
# RUN bactopia download --use-defaults --verbose --wf ngmaster
# RUN bactopia download --use-defaults --verbose --wf panaroo
# RUN bactopia download --use-defaults --verbose --wf phyloflash
# RUN bactopia download --use-defaults --verbose --wf pirate
# RUN bactopia download --use-defaults --verbose --wf plasmidfinder
# RUN bactopia download --use-defaults --verbose --wf prokka
# RUN bactopia download --use-defaults --verbose --wf rgi
# RUN bactopia download --use-defaults --verbose --wf roary
# RUN bactopia download --use-defaults --verbose --wf scoary
# RUN bactopia download --use-defaults --verbose --wf seqsero2
# RUN bactopia download --use-defaults --verbose --wf seroba
# RUN bactopia download --use-defaults --verbose --wf shigatyper
# RUN bactopia download --use-defaults --verbose --wf sistr
# RUN bactopia download --use-defaults --verbose --wf snippy
# RUN bactopia download --use-defaults --verbose --wf snpdists
# RUN bactopia download --use-defaults --verbose --wf spatyper
# RUN bactopia download --use-defaults --verbose --wf ssuissero
# RUN bactopia download --use-defaults --verbose --wf staphopiasccmec
# RUN bactopia download --use-defaults --verbose --wf tbprofiler

# Clean conda cache etc.
# NOTE: don't do this after installing each workflow as some of the dependencies are shared.
# Therefore, their removal at each layer would cause their re-download/installation later on.
RUN conda clean --all -y


# multi stage to reduce docker image size and avoid conda env activation
FROM debian:buster-slim

# Copy the programs installed
COPY --from=condabuild /opt/conda/envs/custom_env /opt/conda/envs/custom_env

ENV PATH=/opt/conda/envs/custom_env/bin:$PATH

# ps isn't in the base debian images - required by GATHER_SAMPLES
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*
