FROM condaforge/mambaforge:23.3.1-1 AS condabuild

ARG pathogen
COPY docker/${pathogen}/ncov2019-artic-nf/environments/illumina/environment.yml /environment.yml
RUN mamba env create -f /environment.yml -n custom_env \
  && conda clean --all -y


FROM debian:bookworm-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends procps rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/custom_env /opt/conda/envs/custom_env

ENV PATH=/ncov2019-artic-nf/bin:/opt/conda/envs/custom_env/bin:$PATH
# otherwise python click complains
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ARG pathogen
COPY docker/${pathogen}/ncov2019-artic-nf /ncov2019-artic-nf
COPY psga/${pathogen}/ncov-illumina.config psga/${pathogen}/ncov-common.config /
COPY data/${pathogen}/ncov2019-artic-nf/* /
COPY data/${pathogen}/primer_schemes /primer_schemes
COPY scripts/ncov /app/scripts/ncov
