FROM python:3.9

RUN apt-get update \
  && apt-get install --yes --no-install-recommends build-essential procps wget default-jre openjdk-11-jre-headless libpq-dev rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# fetch a version of nextflow including the nf-amazon plugin. Install the nf-amazon plugin once for all
ENV NXF_VER="22.05.0-edge"
RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v${NXF_VER}/nextflow-${NXF_VER}-all | bash \
  && chmod +x nextflow \
  && mv nextflow /usr/bin \
  && nextflow plugins install nf-amazon

# install fastqc
ENV FASTQC_VERSION="0.11.9"
RUN cd /usr/local \
  && wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${FASTQC_VERSION}.zip \
  && unzip fastqc_v${FASTQC_VERSION}.zip \
  && chmod 755 FastQC/fastqc \
  && ln -s /usr/local/FastQC/fastqc /usr/local/bin/fastqc \
  && rm fastqc_v${FASTQC_VERSION}.zip
# overwrite fastqc configuration so that we only run the QC tests we need
COPY data/fastqc_config_limits.txt /usr/local/FastQC/Configuration/limits.txt
