FROM condaforge/mambaforge:4.14.0-0 AS condabuild

ARG pathogen
COPY docker/${pathogen}/read-it-and-keep.yml /environment.yml

RUN mamba env create -f /environment.yml -n custom_env \
  && conda clean --all -y

ENV PATH=/opt/conda/envs/custom_env/bin:$PATH

# copy the reference genome MN908947.3 without poly-A tail
# see: https://www.biorxiv.org/content/10.1101/2022.01.21.477194v1
COPY data/MN908947.3.no_poly_A.fa /
