FROM continuumio/miniconda3:4.10.3 AS condabuild

ARG ncov=ncov2019-artic-nf
ARG ncov_commit=8af5152cf7107c3a369b996f5bad3473d329050c
ARG primer_schemes_commit=c40e75dd532fa1241c0af480c378c9cc07abb915

RUN git clone --recursive https://github.com/connor-lab/${ncov}.git \
  && cd ${ncov} \
  && git checkout ${ncov_commit}

# Also reinstall these two packages to their latest version, as the conda-selected downgraded ones fail to run
RUN cd ${ncov}/environments \
  && conda install mamba -c conda-forge \
  && mamba env create -f illumina/environment.yml \
  && mamba env update -f extras.yml -n artic-ncov2019-illumina \
  && mamba install -y -c conda-forge -c bioconda cutadapt==3.1 dnaio==0.4.4 openjdk=11.0.8 -n artic-ncov2019-illumina


FROM debian:buster-slim
RUN apt-get update \
  && apt-get install -y git procps wget rename \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=condabuild /opt/conda/envs/artic-ncov2019-illumina /opt/conda/envs/artic-ncov2019-illumina
COPY --from=condabuild ${ncov} ${ncov}
ENV PATH=${ncov}/bin:/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH


# PRIMERS
# Store primers in ncov dockerfile with path:
# /primers/${primer_name}/SARS-CoV-2/${primer_version}
# e.g. --kit ARTIC_V4 will use the primers stored in: /primers/ARTIC/SARS-CoV-2/V4
# This path must contain:
# 1) *.primer.bed
# 2) *.reference.fasta
RUN mkdir -p /primers \
  && git clone https://github.com/artic-network/primer-schemes.git /primers/ARTIC \
  && cd /primers/ARTIC \
  && git checkout ${primer_schemes_commit}


COPY psga/sars_cov_2/ncov-illumina.config .
COPY psga/sars_cov_2/ncov-common.config .

RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v21.10.6/nextflow | bash && chmod +x nextflow && mv nextflow /usr/bin
