FROM python:3.9

RUN apt-get update \
  && apt-get install --yes --no-install-recommends build-essential procps wget default-jre openjdk-11-jre-headless libpq-dev rename liblzma-dev libbz2-dev zlib1g-dev \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*


# fetch a version of nextflow including the nf-amazon plugin. Install the nf-amazon plugin once for all
ENV NXF_VER="22.08.0-edge"
RUN wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v${NXF_VER}/nextflow-${NXF_VER}-all | bash \
  && chmod +x nextflow \
  && mv nextflow /usr/bin \
  && nextflow plugins install nf-amazon@1.10.0

RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/1.12.129/aws-java-sdk-sts-1.12.129.jar \
  && mv aws-java-sdk-sts-1.12.129.jar ~/.nextflow/plugins/nf-amazon-1.10.0/lib/aws-java-sdk-sts-1.12.129.jar


# install fastqc
ENV FASTQC_VERSION="0.11.9"
RUN cd /usr/local \
  && wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${FASTQC_VERSION}.zip \
  && unzip fastqc_v${FASTQC_VERSION}.zip \
  && chmod 755 FastQC/fastqc \
  && ln -s /usr/local/FastQC/fastqc /usr/local/bin/fastqc \
  && rm fastqc_v${FASTQC_VERSION}.zip
# overwrite fastqc configuration so that we only run the QC tests we need
COPY data/fastqc_config_limits.txt /usr/local/FastQC/Configuration/limits.txt


# install read-it-and-keep (tool for human reads removal)
# Notes:
# a) the instructions for Dockerfile, docker pull and conda available with read-it-and-keep are broken..
# b) this block fixes the original installer and customise what we need
# c) these dependencies (see head of this file for reference) are required only by the code below:
#    - apt-get deps: liblzma-dev libbz2-dev zlib1g-dev
#    - python deps: pyfastaq
ENV READ_IT_AND_KEEP_VERSION="0.3.0"
ENV READ_IT_AND_KEEP_DIR="/usr/local/read-it-and-keep"
ARG READ_IT_AND_KEEP_SRC_DIR="/usr/local/read-it-and-keep-${READ_IT_AND_KEEP_VERSION}"
ENV PATH=${READ_IT_AND_KEEP_DIR}:$PATH
ENV LANG=C.UTF-8
RUN mkdir -p ${READ_IT_AND_KEEP_DIR} \
  && cd /usr/local/ \
  && wget https://github.com/GlobalPathogenAnalysisService/read-it-and-keep/archive/refs/tags/v${READ_IT_AND_KEEP_VERSION}.tar.gz \
  && tar xzf v${READ_IT_AND_KEEP_VERSION}.tar.gz \
  && rm v${READ_IT_AND_KEEP_VERSION}.tar.gz \
  && pip3 install pyfastaq \
  && cd ${READ_IT_AND_KEEP_SRC_DIR}/src \
  && make \
  && cd ${READ_IT_AND_KEEP_DIR} \
  && cp -s ${READ_IT_AND_KEEP_SRC_DIR}/src/readItAndKeep . \
  && cp -s ${READ_IT_AND_KEEP_SRC_DIR}/tests/MN908947.3.fa . \
  && cp -s ${READ_IT_AND_KEEP_SRC_DIR}/tests/MN908947.3.no_poly_A.fa . \
