/*
 * samples per test: 2
 * processing time: few minutes
 */
pipeline {
    agent none
    environment {
        PSGA_PIPELINE = "psga-pipeline-sars-cov-2"
    }
    stages {
        stage('Run PSGA pipeline: small tests') {
            parallel {
                stage('illumina/v3') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/small_tests/illumina/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/illumina_short"),
                                        string(name: 'NXF_WORK', value: "/data/work/illumina_short"),
                                        string(name: 'ANALYSIS_RUN', value: "illumina_short"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "illumina"),
                                        string(name: 'KIT', value: "ARTIC_V3"),
                                ]
                            )
                        }
                    }
                }
                stage('ont/v3') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/small_tests/ont/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/ont_short"),
                                        string(name: 'NXF_WORK', value: "/data/work/ont_short"),
                                        string(name: 'ANALYSIS_RUN', value: "ont_short"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "ont"),
                                        string(name: 'KIT', value: "ARTIC_V3"),
                                ]
                            )
                        }
                    }
                }
                stage('illumina/v4') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/requirements/CL0015b/illumina_v4_input/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/illumina_v4"),
                                        string(name: 'NXF_WORK', value: "/data/work/illumina_v4"),
                                        string(name: 'ANALYSIS_RUN', value: "illumina_v4"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "illumina"),
                                        string(name: 'KIT', value: "ARTIC_V4"),
                                ]
                            )
                        }
                    }
                }
                stage('ont/v4') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/requirements/CL0015b/ont_v4_input/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/ont_v4"),
                                        string(name: 'NXF_WORK', value: "/data/work/ont_v4"),
                                        string(name: 'ANALYSIS_RUN', value: "ont_v4"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "ont"),
                                        string(name: 'KIT', value: "ARTIC_V4"),
                                ]
                            )
                        }
                    }
                }
                stage('illumina/v4.1') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/requirements/CL0015b/illumina_v4_1_input/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/illumina_v4_1"),
                                        string(name: 'NXF_WORK', value: "/data/work/illumina_v4_1"),
                                        string(name: 'ANALYSIS_RUN', value: "illumina_v4_1"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "illumina"),
                                        string(name: 'KIT', value: "ARTIC_V4.1"),
                                ]
                            )
                        }
                    }
                }
                stage('ont/v4.1') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/requirements/CL0015b/ont_v4_1_input/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/ont_v4_1"),
                                        string(name: 'NXF_WORK', value: "/data/work/ont_v4_1"),
                                        string(name: 'ANALYSIS_RUN', value: "ont_v4_1"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "ont"),
                                        string(name: 'KIT', value: "ARTIC_V4.1"),
                                ]
                            )
                        }
                    }
                }
                stage('fasta') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/small_tests/unknown/metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/unknown_short"),
                                        string(name: 'NXF_WORK', value: "/data/work/unknown_short"),
                                        string(name: 'ANALYSIS_RUN', value: "unknown_short"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "unknown"),
                                        string(name: 'KIT', value: "ARTIC_V3"),
                                ]
                            )
                        }
                    }
                }
                stage('failing_illumina_samples') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: false),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/from_them/gold_standard/illumina/v4/2022-08-18/pipeline_metadata.csv"),
                                        string(name: 'OUTPUT_PATH', value: "/data/output/empty_sample_and_sample_failing_ncov_qc"),
                                        string(name: 'NXF_WORK', value: "/data/work/empty_sample_and_sample_failing_ncov_qc"),
                                        string(name: 'ANALYSIS_RUN', value: "empty_sample_and_sample_failing_ncov_qc"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "illumina"),
                                        string(name: 'KIT', value: "V4"),
                                ]
                            )
                        }
                    }
                }            }
        }
    }
}
