/*
 * samples per test: 2
 * processing time: few minutes
 */
pipeline {
    agent none
    environment {
        PSGA_PIPELINE = "psga-pipeline-sars-cov-2"
    }
    stages {
        stage('Run PSGA pipeline: small tests') {
            parallel {
                stage('illumina') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/small_tests/illumina/metadata.csv"),
                                        string(name: 'PSGA_OUTPUT_PATH', value: "/data/output/illumina_short"),
                                        string(name: 'NXF_WORK', value: "/data/work/illumina_short"),
                                        string(name: 'ANALYSIS_RUN', value: "illumina_short"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "illumina"),
                                ]
                            )
                        }
                    }
                }
                stage('ont') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/small_tests/ont/metadata.csv"),
                                        string(name: 'PSGA_OUTPUT_PATH', value: "/data/output/ont_short"),
                                        string(name: 'NXF_WORK', value: "/data/work/ont_short"),
                                        string(name: 'ANALYSIS_RUN', value: "ont_short"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "ont"),
                                ]
                            )
                        }
                    }
                }
                stage('fasta') {
                    steps {
                        script {
                            build (
                                job: "${PSGA_PIPELINE}/${env.BRANCH_NAME}",
                                parameters: [
                                        booleanParam(name: 'VALIDATION_TEST', value: true),
                                        string(name: 'METADATA', value: "s3://synthetic-data-dev/UKHSA/small_tests/unknown/metadata.csv"),
                                        string(name: 'PSGA_OUTPUT_PATH', value: "/data/output/unknown_short"),
                                        string(name: 'NXF_WORK', value: "/data/work/unknown_short"),
                                        string(name: 'ANALYSIS_RUN', value: "unknown_short"),
                                        string(name: 'SEQUENCING_TECHNOLOGY', value: "unknown"),
                                ]
                            )
                        }
                    }
                }
            }
        }
    }
}
