-- Deploy ps-bahrain-covid:08-add_area_colours to pg

BEGIN;

  SET LOCAL search_path = sars_cov_2;

  UPDATE area SET colour = e'\\x5E1D9D' WHERE name = 'ZINJ';
  UPDATE area SET colour = e'\\x5A1DA0' WHERE name = 'ZAYED TOWN';
  UPDATE area SET colour = e'\\x571EA3' WHERE name = 'ZALLAQ';
  UPDATE area SET colour = e'\\x531EA6' WHERE name = 'WADIYAN';
  UPDATE area SET colour = e'\\x501EA9' WHERE name = 'WADI ALI';
  UPDATE area SET colour = e'\\x4E20AB' WHERE name = 'UMMHAZWARAH';
  UPDATE area SET colour = e'\\x4D22AE' WHERE name = 'UMM JIDR AL SUMMAN';
  UPDATE area SET colour = e'\\x4C25B0' WHERE name = 'UMM JIDR';
  UPDATE area SET colour = e'\\x4A27B2' WHERE name = e'UMM AL NA\'SAN';
  UPDATE area SET colour = e'\\x492AB5' WHERE name = 'UM AL BAIDH';
  UPDATE area SET colour = e'\\x472CB7' WHERE name = 'TUBLI';
  UPDATE area SET colour = e'\\x462EB9' WHERE name = 'TASHAN';
  UPDATE area SET colour = e'\\x4531BC' WHERE name = 'TARRAFI';
  UPDATE area SET colour = e'\\x4333BE' WHERE name = 'SUWAD AL SHAMALIYAH';
  UPDATE area SET colour = e'\\x4236C0' WHERE name = 'SUWAD AL JANUBIYAH';
  UPDATE area SET colour = e'\\x4138C3' WHERE name = 'SUFALA';
  UPDATE area SET colour = e'\\x403BC4' WHERE name = 'SOUTH SEHLA';
  UPDATE area SET colour = e'\\x403EC6' WHERE name = 'SHARQ AL HIDD UM AL SHAJAR';
  UPDATE area SET colour = e'\\x4041C7' WHERE name = 'SHARQ AL HIDD UM AL SAWALI';
  UPDATE area SET colour = e'\\x3F44C8' WHERE name = 'SHARQ AL HIDD AL QULYAH';
  UPDATE area SET colour = e'\\x3F47C9' WHERE name = 'SHARQ AL HIDD AL EZEL';
  UPDATE area SET colour = e'\\x3F4ACA' WHERE name = 'SHAKHURAH';
  UPDATE area SET colour = e'\\x3F4DCB' WHERE name = 'SHAHRAKKAN';
  UPDATE area SET colour = e'\\x3F50CC' WHERE name = 'SAR';
  UPDATE area SET colour = e'\\x3F53CD' WHERE name = 'SANAD';
  UPDATE area SET colour = e'\\x3F56CE' WHERE name = 'SANABIS';
  UPDATE area SET colour = e'\\x3E59CF' WHERE name = 'SAMAHEEJ';
  UPDATE area SET colour = e'\\x3E5CD0' WHERE name = 'SALMAN TOWN';
  UPDATE area SET colour = e'\\x3F5ED0' WHERE name = 'SALIMABAD';
  UPDATE area SET colour = e'\\x3F61D0' WHERE name = 'SALIHIYA';
  UPDATE area SET colour = e'\\x4064CF' WHERE name = 'SAFREH';
  UPDATE area SET colour = e'\\x4067CF' WHERE name = 'SADAD';
  UPDATE area SET colour = e'\\x416ACF' WHERE name = 'RUBUD AL SHARQIYAH';
  UPDATE area SET colour = e'\\x416CCE' WHERE name = 'RUBUD AL GHARBIYAH';
  UPDATE area SET colour = e'\\x426FCE' WHERE name = 'RIFFA MOASKAR';
  UPDATE area SET colour = e'\\x4272CE' WHERE name = 'RIFFA / WADI ALSAIL';
  UPDATE area SET colour = e'\\x4375CD' WHERE name = 'RIFFA / SWAYFRA';
  UPDATE area SET colour = e'\\x4377CD' WHERE name = e'RIFFA / MO\'ASKAR';
  UPDATE area SET colour = e'\\x447ACD' WHERE name = 'RIFFA / JARYALSHAIKH';
  UPDATE area SET colour = e'\\x447DCC' WHERE name = 'RIFFA / BUKOWARAH';
  UPDATE area SET colour = e'\\x457FCB' WHERE name = 'RIFFA / ALSHARGI';
  UPDATE area SET colour = e'\\x4681C9' WHERE name = 'RIFFA / ALROWDHA';
  UPDATE area SET colour = e'\\x4783C8' WHERE name = 'RIFFA / ALHUNAYNIYAH';
  UPDATE area SET colour = e'\\x4886C7' WHERE name = 'RIFFA / ALHAJIYAT';
  UPDATE area SET colour = e'\\x4988C5' WHERE name = 'RIFFA / ALGHARBI';
  UPDATE area SET colour = e'\\x498AC4' WHERE name = 'RIFFA / AL SHAMALI';
  UPDATE area SET colour = e'\\x4A8CC2' WHERE name = 'RIFFA / AL BUHAIR';
  UPDATE area SET colour = e'\\x4B8EC1' WHERE name = 'RAS ZUWAYED';
  UPDATE area SET colour = e'\\x4C91C0' WHERE name = 'RAS HAYYAN';
  UPDATE area SET colour = e'\\x4D93BE' WHERE name = 'RAS ABU JARJUR';
  UPDATE area SET colour = e'\\x4E95BD' WHERE name = 'QALALI';
  UPDATE area SET colour = e'\\x4F97BB' WHERE name = 'NURANA ISLAND';
  UPDATE area SET colour = e'\\x5098B9' WHERE name = 'NORTH SEHLA';
  UPDATE area SET colour = e'\\x519AB7' WHERE name = 'NABIH SALEH';
  UPDATE area SET colour = e'\\x539BB5' WHERE name = 'MUZARRA';
  UPDATE area SET colour = e'\\x549DB3' WHERE name = 'MURQOBAN';
  UPDATE area SET colour = e'\\x559EB1' WHERE name = 'MUHARRAQ';
  UPDATE area SET colour = e'\\x56A0AE' WHERE name = 'MOHAMMADIYAH';
  UPDATE area SET colour = e'\\x57A1AC' WHERE name = 'MAQABAH';
  UPDATE area SET colour = e'\\x59A3AA' WHERE name = 'MANAMA/MINA SALMAN INDUSTRIAL AREA';
  UPDATE area SET colour = e'\\x5AA5A8' WHERE name = 'MANAMA CENTER';
  UPDATE area SET colour = e'\\x5BA6A6' WHERE name = 'MANAMA / UMM ALHASSAM';
  UPDATE area SET colour = e'\\x5CA8A4' WHERE name = 'MANAMA / SEA FRONT';
  UPDATE area SET colour = e'\\x5EA9A2' WHERE name = 'MANAMA / BUGHAZAL';
  UPDATE area SET colour = e'\\x5FAA9F' WHERE name = 'MANAMA / BUASHIRAH';
  UPDATE area SET colour = e'\\x61AB9D' WHERE name = 'MANAMA / ALSUWAYFIYAH';
  UPDATE area SET colour = e'\\x63AC9B' WHERE name = 'MANAMA / ALSUQAYYAH';
  UPDATE area SET colour = e'\\x64AD98' WHERE name = 'MANAMA / ALSALMANIYA';
  UPDATE area SET colour = e'\\x66AE96' WHERE name = 'MANAMA / ALQUDAYBIYAH';
  UPDATE area SET colour = e'\\x67AF94' WHERE name = e'MANAMA / ALNAI\'M';
  UPDATE area SET colour = e'\\x69B091' WHERE name = 'MANAMA / ALMAHUZ';
  UPDATE area SET colour = e'\\x6AB18F' WHERE name = 'MANAMA / ALJUFFAIR';
  UPDATE area SET colour = e'\\x6CB28D' WHERE name = 'MANAMA / ALHOORA';
  UPDATE area SET colour = e'\\x6DB38A' WHERE name = 'MANAMA / ALGUFUL';
  UPDATE area SET colour = e'\\x6FB388' WHERE name = 'MANAMA / ALGHURAYFAH';
  UPDATE area SET colour = e'\\x71B486' WHERE name = 'MANAMA / ALFATEH';
  UPDATE area SET colour = e'\\x73B584' WHERE name = 'MANAMA / ALCORNICHE';
  UPDATE area SET colour = e'\\x75B581' WHERE name = 'MANAMA / AL ADLIYAH';
  UPDATE area SET colour = e'\\x76B67F' WHERE name = 'MAMLAHAT AL MAMTALAH';
  UPDATE area SET colour = e'\\x78B77D' WHERE name = 'MALKIYA';
  UPDATE area SET colour = e'\\x7AB77B' WHERE name = 'MAHAZZAH';
  UPDATE area SET colour = e'\\x7CB879' WHERE name = 'MADINAT KHALIFA ALULAIM';
  UPDATE area SET colour = e'\\x7EB876' WHERE name = 'MADINAT KHALIFA ALMAHADIR';
  UPDATE area SET colour = e'\\x80B974' WHERE name = 'MADINAT HAMAD';
  UPDATE area SET colour = e'\\x82BA72' WHERE name = 'LHASSAY';
  UPDATE area SET colour = e'\\x83BA70' WHERE name = 'KING FAHAD CAUSWAY';
  UPDATE area SET colour = e'\\x86BB6E' WHERE name = 'KHAMIS';
  UPDATE area SET colour = e'\\x88BB6C' WHERE name = 'KARZAKKAN';
  UPDATE area SET colour = e'\\x8ABB6A' WHERE name = 'KARRANAH';
  UPDATE area SET colour = e'\\x8CBB69' WHERE name = 'KARBABAD';
  UPDATE area SET colour = e'\\x8EBC67' WHERE name = 'JUZUR AL DAR';
  UPDATE area SET colour = e'\\x90BC65' WHERE name = 'JIDHAFS';
  UPDATE area SET colour = e'\\x92BC63' WHERE name = 'JIDDAH';
  UPDATE area SET colour = e'\\x94BD61' WHERE name = 'JIDD ALI';
  UPDATE area SET colour = e'\\x96BD60' WHERE name = 'JID AL HAJ';
  UPDATE area SET colour = e'\\x98BD5E' WHERE name = 'JERDAB';
  UPDATE area SET colour = e'\\x9ABE5C' WHERE name = 'JEBLAT HIBSHI';
  UPDATE area SET colour = e'\\x9DBE5A' WHERE name = 'JAZIRAT HAWAR';
  UPDATE area SET colour = e'\\x9FBE59' WHERE name = 'JAZAER BEACH';
  UPDATE area SET colour = e'\\xA1BE58' WHERE name = 'JAU';
  UPDATE area SET colour = e'\\xA3BE57' WHERE name = 'JANNUSAN';
  UPDATE area SET colour = e'\\xA5BE55' WHERE name = 'ISA TOWN';
  UPDATE area SET colour = e'\\xA7BE54' WHERE name = 'INDUSTRIAL AREA';
  UPDATE area SET colour = e'\\xAABD53' WHERE name = 'HILLAT ABDULSALEH';
  UPDATE area SET colour = e'\\xACBD51' WHERE name = 'HIDD AL JAMAL';
  UPDATE area SET colour = e'\\xAEBD50' WHERE name = 'HIDD';
  UPDATE area SET colour = e'\\xB0BD4F' WHERE name = 'HAWRAT SANAD';
  UPDATE area SET colour = e'\\xB2BD4D' WHERE name = 'HAWRAT INGAH';
  UPDATE area SET colour = e'\\xB4BD4C' WHERE name = 'HAWRAT A ALI';
  UPDATE area SET colour = e'\\xB6BD4B' WHERE name = 'HALAT AL SLETAH';
  UPDATE area SET colour = e'\\xB8BC4A' WHERE name = 'HALAT AL NEAIM';
  UPDATE area SET colour = e'\\xBABC4A' WHERE name = 'HAFIRAH';
  UPDATE area SET colour = e'\\xBCBB49' WHERE name = 'DURRAT AL BAHRAIN';
  UPDATE area SET colour = e'\\xBEBB48' WHERE name = 'DIYAR AL MUHARRAQ';
  UPDATE area SET colour = e'\\xC0BA47' WHERE name = 'DIPLOMATIC AREA';
  UPDATE area SET colour = e'\\xC2BA46' WHERE name = 'DILMUNIA ISLAND';
  UPDATE area SET colour = e'\\xC4B945' WHERE name = 'DAR KULAIB';
  UPDATE area SET colour = e'\\xC6B944' WHERE name = 'DAMISTAN';
  UPDATE area SET colour = e'\\xC8B944' WHERE name = 'BUSAITEEN';
  UPDATE area SET colour = e'\\xCAB843' WHERE name = 'BURI';
  UPDATE area SET colour = e'\\xCCB742' WHERE name = 'BUDAIYA';
  UPDATE area SET colour = e'\\xCDB642' WHERE name = 'BU QUWAH';
  UPDATE area SET colour = e'\\xCFB541' WHERE name = 'BILAD AL QADEEM';
  UPDATE area SET colour = e'\\xD0B441' WHERE name = 'BAR BAR';
  UPDATE area SET colour = e'\\xD2B340' WHERE name = 'BANI JAMRAH';
  UPDATE area SET colour = e'\\xD3B23F' WHERE name = 'BANDER AL SEEF';
  UPDATE area SET colour = e'\\xD5B03F' WHERE name = 'Area';
  UPDATE area SET colour = e'\\xD6AF3E' WHERE name = 'AWALI';
  UPDATE area SET colour = e'\\xD8AE3E' WHERE name = 'ASKAR';
  UPDATE area SET colour = e'\\xD9AD3D' WHERE name = 'ARAD';
  UPDATE area SET colour = e'\\xDBAC3D' WHERE name = 'AMWAJ';
  UPDATE area SET colour = e'\\xDCAB3C' WHERE name = 'AL SHABAK';
  UPDATE area SET colour = e'\\xDDA93C' WHERE name = 'AL SEEF';
  UPDATE area SET colour = e'\\xDEA73B' WHERE name = 'AL SAYH';
  UPDATE area SET colour = e'\\xDFA53B' WHERE name = 'AL SAKHIR';
  UPDATE area SET colour = e'\\xE0A33A' WHERE name = 'AL SAFRIYAH';
  UPDATE area SET colour = e'\\xE1A13A' WHERE name = 'AL RUMAYTHAH';
  UPDATE area SET colour = e'\\xE19F3A' WHERE name = 'AL RUMAMIN';
  UPDATE area SET colour = e'\\xE29D39' WHERE name = 'AL RIFFAH';
  UPDATE area SET colour = e'\\xE39B39' WHERE name = 'AL RAMLI';
  UPDATE area SET colour = e'\\xE49938' WHERE name = 'AL QURAYYAH';
  UPDATE area SET colour = e'\\xE59738' WHERE name = 'AL QURAYN';
  UPDATE area SET colour = e'\\xE69537' WHERE name = 'AL QARYAH';
  UPDATE area SET colour = e'\\xE69337' WHERE name = 'AL QARAH';
  UPDATE area SET colour = e'\\xE69036' WHERE name = e'AL QAL\'AH';
  UPDATE area SET colour = e'\\xE68D36' WHERE name = 'AL QADAM';
  UPDATE area SET colour = e'\\xE68A35' WHERE name = 'AL NUWAIDRAT';
  UPDATE area SET colour = e'\\xE68735' WHERE name = 'AL NASFA';
  UPDATE area SET colour = e'\\xE68434' WHERE name = 'AL MUSALLA';
  UPDATE area SET colour = e'\\xE68234' WHERE name = 'AL MAZROWIAH';
  UPDATE area SET colour = e'\\xE67F33' WHERE name = 'AL MARKH';
  UPDATE area SET colour = e'\\xE67C32' WHERE name = 'AL MAQSHA';
  UPDATE area SET colour = e'\\xE67932' WHERE name = 'AL MAMTALAH';
  UPDATE area SET colour = e'\\xE67631' WHERE name = e'AL MA\'AMEER';
  UPDATE area SET colour = e'\\xE67331' WHERE name = 'AL LAWZI';
  UPDATE area SET colour = e'\\xE67030' WHERE name = 'AL KHARIJIYAH';
  UPDATE area SET colour = e'\\xE56C2F' WHERE name = 'AL JASRAH';
  UPDATE area SET colour = e'\\xE4682F' WHERE name = 'AL JANABIYAH';
  UPDATE area SET colour = e'\\xE4652E' WHERE name = e'AL JA\'SIRAH';
  UPDATE area SET colour = e'\\xE3612D' WHERE name = 'AL HAMRIYA';
  UPDATE area SET colour = e'\\xE35E2D' WHERE name = 'AL HAMALAH';
  UPDATE area SET colour = e'\\xE25A2C' WHERE name = 'AL HAJAR';
  UPDATE area SET colour = e'\\xE2572B' WHERE name = 'AL GHAYNAH';
  UPDATE area SET colour = e'\\xE1532B' WHERE name = 'AL DUR';
  UPDATE area SET colour = e'\\xE14F2A' WHERE name = 'AL DIRAZ';
  UPDATE area SET colour = e'\\xE04C29' WHERE name = 'AL DAIR';
  UPDATE area SET colour = e'\\xE04829' WHERE name = 'AL DAIH';
  UPDATE area SET colour = e'\\xDF4528' WHERE name = 'AL BURHAMA';
  UPDATE area SET colour = e'\\xDF4127' WHERE name = 'AL AMUR';
  UPDATE area SET colour = e'\\xDE3E27' WHERE name = 'AL AKR AL SHARQI';
  UPDATE area SET colour = e'\\xDE3A26' WHERE name = 'AL AKR AL GHARBI';
  UPDATE area SET colour = e'\\xDD3625' WHERE name = 'ADHARI';
  UPDATE area SET colour = e'\\xDD3325' WHERE name = 'ABU SAYBA';
  UPDATE area SET colour = e'\\xDC2F24' WHERE name = 'ABU BHAM';
  UPDATE area SET colour = e'\\xDC2C23' WHERE name = e'ABU AL \'AYASH';
  UPDATE area SET colour = e'\\xDB2823' WHERE name = e'A\'ALI';

COMMIT;
