
Vagrant.configure("2") do |config|
    # centos config
    config.vm.define "centos" do |centos|
      centos.vm.box = "geerlingguy/centos7"
        centos.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = 2048
          vb.cpus = 2
      end

      config.vm.synced_folder "../../psga/", "/home/vagrant/psga/"
      config.vm.provision "shell", inline: "yum install python3 python3-pip -y"
      config.vm.provision "shell", privileged: false, inline: "pip3 install ansible --user"
      # centos.vm.provision "ansible" do |ansible|
      #   ansible.playbook = "test/test.yml"
      #   ansible.extra_vars = {
      #     pipeline_user: "pipeline"
      #   }
      #   ansible.verbose = true
      # end
    end
  end
